name: Scheduled Tweet Processing

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  process-tweets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Process Scheduled Tweets
        run: |
          curl -X POST ${{ secrets.APP_URL }}/api/cron/process-scheduled-tweets \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json"